uploaded helpdesk_ticket module
DarioLodeiros/learning_helpdesk pull request #1
Opened 2020-07-16 11:57 UTC by castares

My helpdesk ticket as it is today.

2020-07-21 15:14 UTC, DarioLodeiros requested changes

2020-07-21 15:14 UTC, DarioLodeiros commented on helpdesk_factorlibre/models/helpdesk_ticket.py
> +        ('Zero', _('Sin prioridad')),
Not use Spanish on the code

2020-07-23 08:17 UTC, castares commented on helpdesk_factorlibre/models/helpdesk_ticket.py
> +        ('Zero', _('Sin prioridad')),
Changed to English

2020-07-28 09:59 UTC, DarioLodeiros approved these changes

2020-07-28 11:12 UTC, merged